name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2        
      - name: install dependencies
        run: npm ci
      - name: run build
        run:  npm run build